# vim:ts=2:sw=2:et

dist: trusty

language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

services:
  - postgresql

before_script:
  - composer update --dev
  - psql -c "CREATE DATABASE test;" -U postgres
  - psql -c "CREATE USER test WITH ENCRYPTED PASSWORD 'test'; GRANT ALL PRIVILEGES ON DATABASE test TO test;" -U postgres

script:
  - cd test && ../vendor/bin/run_unit_tests
