# vim:ts=2:sw=2:et
os: linux

# Partner Queue Solution, no credits are consumed
arch: ppc64le

language: php

addons:
  postgresql: "9.6"

jobs:
  include:
    - php: 7.1
      dist: xenial
    - php: 7.2
      dist: xenial
    - php: 7.3
      dist: xenial
    - php: 7.4
      dist: focal
      addons:
        postgresql: "12"
    - php: 8.0
      dist: focal
      addons:
        postgresql: "12"
    - php: 8.1
      dist: focal
      addons:
        postgresql: "12"

before_script:
  - composer update --dev
  - sudo -u postgres psql -c "CREATE DATABASE test;" -U postgres 2>&1
  - sudo -u postgres psql -c "CREATE USER test WITH ENCRYPTED PASSWORD 'test'" -U postgres 2>&1
  - sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE test TO test" -U postgres 2>&1
  - sudo -u postgres psql -c "GRANT ALL ON SCHEMA public TO test" -U postgres test 2>&1

script:
  - cd test && ../vendor/bin/run_unit_tests
