# vim:ts=2:sw=2:et
os: linux

# Partner Queue Solution, no credits are consumed
arch: ppc64le

language: php

jobs:
  include:
    - php: 7.1
      dist: xenial
    - php: 7.2
      dist: xenial
    - php: 7.3
      dist: xenial
    - php: 7.4
      dist: focal
    - php: 8.0
      dist: focal
    - php: 8.1
      dist: focal

services:
  - postgresql

before_script:
  - composer update --dev
  - sudo -u postgres psql -c "CREATE DATABASE test;" -U postgres
  - sudo -u postgres psql -c "CREATE USER test WITH ENCRYPTED PASSWORD 'test'; GRANT ALL PRIVILEGES ON DATABASE test TO test;" -U postgres

script:
  - cd test && ../vendor/bin/run_unit_tests
